SELECT TOP (1000) [id]
      ,[loanamount]
      ,[interestrate]
      ,[term]
      ,[homevalue]
      ,[monthlypayment]
      ,[totalinterest]
      ,[datesubmitted]
  FROM [loanaccounts].[dbo].[loans]
